# Site settings
title: "Piano Lessons with Arthur Lui"
short_title: "Piano with Arthur"
email: luiarthur@gmail.com
description: "Piano lessons with Arthur Lui"
# disqus_shortname: "" # defaults to "<github-user-name>githubio"
github_repo: https://github.com/luiarthur/piano
google_analytics: G-RJBL4JRZQ8


plugins:
  # search engine optimization
  - jekyll-seo-tag
  # create sitemap
  - jekyll-sitemap

# Build settings
markdown: kramdown
permalink: /:title

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      comments: true

# To include special collections:
#   create a dir called _mycollections, and put things there
# You can replace `mycollections` with anything
# http://jekyllrb.com/docs/collections/
# NOTE: Uncomment below 
#
# collections:
#   mycollection:
#     output: true
#     permalink: /mycollection/:title/
